### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by escept** [Alex7Kom/node-steam-weblogon#8]
Can you help me with this? I have no idea what it means.
```
buffer.js:179
    throw new TypeError(kFromErrorMsg);
    ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:179:11)
    at new Buffer (buffer.js:154:17)
    at SteamWebLogOn.webLogOn (C:\Users\escept\node_modules\steam-weblogon\index.js:28:7)
    at SteamUser.<anonymous> (C:\Users\escept\buy.js:25:19)
    at emitTwo (events.js:125:13)
    at SteamUser.emit (events.js:213:7)
    at SteamUser._handlers.(anonymous function) (C:\Users\escept\node_modules\steam-user\components\logon.js:310:9)
    at SteamUser._handleMessage (C:\Users\escept\node_modules\steam-user\components\messages.js:216:29)
    at emitThree (events.js:135:13)
    at CMClient.emit (events.js:216:7)
```

**Comment by alex7kom** [comment]
Can you show the part of your code where you call `webLogOn`?

**Comment by escept** [comment]
```
client.logOn(logOnOptions);
client.on('loggedOn', function() {
	console.log("Logged into Steam");
	console.log("Attempting steam-weblogon logon");
    steamWebLogOn.webLogOn(function(webSessionID, cookies){
      console.log("steam-weblogon logon");
    });
```

**Comment by alex7kom** [comment]
node-steam doesn't have an event called `loggedOn`. That code won't run.
Please check the README on 'Usage': https://github.com/Alex7Kom/node-steam-weblogon#usage

**Comment by escept** [comment]
I get the Logged into Steam text though. the code in usage never got called for me.

**Comment by alex7kom** [comment]
This means you are using an outdated (pre-1.x) version of node-steam. node-steam-weblogon is for 1.x.
Luckily for you your version of node-steam [has webLogOn built-in](https://github.com/seishun/node-steam/tree/d92b12e0aa63cde3fa5433a93eafefb752f875cf#weblogoncallback). But I'd recommend to upgrade anyway since it's unsupported. Hope this helps.

**Comment by escept** [comment]
for the client i use node-steam-user though. Is there something i can do with that?

**Comment by alex7kom** [comment]
node-steam-user also has webLogOn: https://github.com/DoctorMcKay/node-steam-user#weblogon
